### Verbo GET – listar todos
GET http://localhost:8000/cliente/ HTTP/1.1

### Verbo GET – listar um
GET http://localhost:8000/cliente/10 HTTP/1.1

### Verbo POST – adicionar
POST http://127.0.0.1:8000/cliente/ HTTP/1.1
content-type: application/json

{
    "nome": ."Coca-Cola",
    "cpf": "058.026.209-00",
    "telefone": "48999990015",
    "compra_fiado": 58.5,
    "dia_fiado": "2023-08-29 15:45:00",
    "senha": "1234"
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/cliente/2 HTTP/1.1
content-type: application/json

{
    "nome": ."Coca-Cola",
    "cpf": "058.026.209-00",
    "telefone": "48999990015",
    "compra_fiado": 58.5,
    "dia_fiado": "2023-08-29 15:45:00",
    "senha": "1234"
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/cliente/3 HTTP/1.1